type_multiplier = {
    # Steel
    ('steel', 'steel'): 0.5,
    ('steel', 'fighting'): 1,
    ('steel', 'dragon'): 1,
    ('steel', 'water'): 0.5,
    ('steel', 'electric'): 0.5,
    ('steel', 'fairy'): 2,
    ('steel', 'fire'): 0.5,
    ('steel', 'ice'): 2,
    ('steel', 'bug'): 1,
    ('steel', 'normal'): 1,
    ('steel', 'grass'): 1,
    ('steel', 'poison'): 1,
    ('steel', 'psychic'): 1,
    ('steel', 'rock'): 2,
    ('steel', 'ground'): 1,
    ('steel', 'ghost'): 1,
    ('steel', 'dark'): 1,
    ('steel', 'flying'): 1,

    # Fighting
    ('fighting', 'steel'): 2,
    ('fighting', 'fighting'): 1,
    ('fighting', 'dragon'): 1,
    ('fighting', 'water'): 1,
    ('fighting', 'electric'): 1,
    ('fighting', 'fairy'): 0.5,
    ('fighting', 'fire'): 1,
    ('fighting', 'ice'): 2,
    ('fighting', 'bug'): 0.5,
    ('fighting', 'normal'): 2,
    ('fighting', 'grass'): 1,
    ('fighting', 'poison'): 0.5,
    ('fighting', 'psychic'): 0.5,
    ('fighting', 'rock'): 2,
    ('fighting', 'ground'): 1,
    ('fighting', 'ghost'): 0,
    ('fighting', 'dark'): 2,
    ('fighting', 'flying'): 0.5,

    # Dragon
    ('dragon', 'steel'): 0.5,
    ('dragon', 'fighting'): 1,
    ('dragon', 'dragon'): 2,
    ('dragon', 'water'): 1,
    ('dragon', 'electric'): 1,
    ('dragon', 'fairy'): 0,
    ('dragon', 'fire'): 1,
    ('dragon', 'ice'): 1,
    ('dragon', 'bug'): 1,
    ('dragon', 'normal'): 1,
    ('dragon', 'grass'): 1,
    ('dragon', 'poison'): 1,
    ('dragon', 'psychic'): 1,
    ('dragon', 'rock'): 1,
    ('dragon', 'ground'): 1,
    ('dragon', 'ghost'): 1,
    ('dragon', 'dark'): 1,
    ('dragon', 'flying'): 1,

    # Water
    ('water', 'steel'): 1,
    ('water', 'fighting'): 1,
    ('water', 'dragon'): 0.5,
    ('water', 'water'): 0.5,
    ('water', 'electric'): 1,
    ('water', 'fairy'): 1,
    ('water', 'fire'): 2,
    ('water', 'ice'): 1,
    ('water', 'bug'): 1,
    ('water', 'normal'): 1,
    ('water', 'grass'): 0.5,
    ('water', 'poison'): 1,
    ('water', 'psychic'): 1,
    ('water', 'rock'): 2,
    ('water', 'ground'): 2,
    ('water', 'ghost'): 1,
    ('water', 'dark'): 1,
    ('water', 'flying'): 1,

    # Electric
    ('electric', 'steel'): 1,
    ('electric', 'fighting'): 1,
    ('electric', 'dragon'): 0.5,
    ('electric', 'water'): 2,
    ('electric', 'electric'): 0.5,
    ('electric', 'fairy'): 1,
    ('electric', 'fire'): 1,
    ('electric', 'ice'): 1,
    ('electric', 'bug'): 1,
    ('electric', 'normal'): 1,
    ('electric', 'grass'): 0.5,
    ('electric', 'poison'): 1,
    ('electric', 'psychic'): 1,
    ('electric', 'rock'): 1,
    ('electric', 'ground'): 0,
    ('electric', 'ghost'): 1,
    ('electric', 'dark'): 1,
    ('electric', 'flying'): 2,

    # Fairy
    ('fairy', 'steel'): 0.5,
    ('fairy', 'fighting'): 2,
    ('fairy', 'dragon'): 2,
    ('fairy', 'water'): 1,
    ('fairy', 'electric'): 1,
    ('fairy', 'fairy'): 1,
    ('fairy', 'fire'): 0.5,
    ('fairy', 'ice'): 1,
    ('fairy', 'bug'): 1,
    ('fairy', 'normal'): 1,
    ('fairy', 'grass'): 1,
    ('fairy', 'poison'): 0.5,
    ('fairy', 'psychic'): 1,
    ('fairy', 'rock'): 1,
    ('fairy', 'ground'): 1,
    ('fairy', 'ghost'): 1,
    ('fairy', 'dark'): 2,
    ('fairy', 'flying'): 1,

    # Fire
    ('fire', 'steel'): 2,
    ('fire', 'fighting'): 1,
    ('fire', 'dragon'): 0.5,
    ('fire', 'water'): 0.5,
    ('fire', 'electric'): 1,
    ('fire', 'fairy'): 1,
    ('fire', 'fire'): 0.5,
    ('fire', 'ice'): 2,
    ('fire', 'bug'): 2,
    ('fire', 'normal'): 1,
    ('fire', 'grass'): 2,
    ('fire', 'poison'): 1,
    ('fire', 'psychic'): 1,
    ('fire', 'rock'): 0.5,
    ('fire', 'ground'): 1,
    ('fire', 'ghost'): 1,
    ('fire', 'dark'): 1,
    ('fire', 'flying'): 1,

    # Ice
    ('ice', 'steel'): 0.5,
    ('ice', 'fighting'): 1,
    ('ice', 'dragon'): 2,
    ('ice', 'water'): 0.5,
    ('ice', 'electric'): 1,
    ('ice', 'fairy'): 1,
    ('ice', 'fire'): 0.5,
    ('ice', 'ice'): 0.5,
    ('ice', 'bug'): 1,
    ('ice', 'normal'): 1,
    ('ice', 'grass'): 2,
    ('ice', 'poison'): 1,
    ('ice', 'psychic'): 1,
    ('ice', 'rock'): 1,
    ('ice', 'ground'): 2,
    ('ice', 'ghost'): 1,
    ('ice', 'dark'): 1,
    ('ice', 'flying'): 2,

    # Bug
    ('bug', 'steel'): 0.5,
    ('bug', 'fighting'): 0.5,
    ('bug', 'dragon'): 1,
    ('bug', 'water'): 1,
    ('bug', 'electric'): 1,
    ('bug', 'fairy'): 0.5,
    ('bug', 'fire'): 0.5,
    ('bug', 'ice'): 1,
    ('bug', 'bug'): 1,
    ('bug', 'normal'): 1,
    ('bug', 'grass'): 2,
    ('bug', 'poison'): 0.5,
    ('bug', 'psychic'): 2,
    ('bug', 'rock'): 1,
    ('bug', 'ground'): 1,
    ('bug', 'ghost'): 0.5,
    ('bug', 'dark'): 2,
    ('bug', 'flying'): 0.5,

    # Normal
    ('normal', 'steel'): 0.5,
    ('normal', 'fighting'): 1,
    ('normal', 'dragon'): 1,
    ('normal', 'water'): 1,
    ('normal', 'electric'): 1,
    ('normal', 'fairy'): 1,
    ('normal', 'fire'): 1,
    ('normal', 'ice'): 1,
    ('normal', 'bug'): 1,
    ('normal', 'normal'): 1,
    ('normal', 'grass'): 1,
    ('normal', 'poison'): 1,
    ('normal', 'psychic'): 1,
    ('normal', 'rock'): 0.5,
    ('normal', 'ground'): 1,
    ('normal', 'ghost'): 0,
    ('normal', 'dark'): 1,
    ('normal', 'flying'): 1,

    # Grass
    ('grass', 'steel'): 0.5,
    ('grass', 'fighting'): 1,
    ('grass', 'dragon'): 0.5,
    ('grass', 'water'): 2,
    ('grass', 'electric'): 1,
    ('grass', 'fairy'): 1,
    ('grass', 'fire'): 0.5,
    ('grass', 'ice'): 1,
    ('grass', 'bug'): 0.5,
    ('grass', 'normal'): 1,
    ('grass', 'grass'): 0.5,
    ('grass', 'poison'): 0.5,
    ('grass', 'psychic'): 1,
    ('grass', 'rock'): 2,
    ('grass', 'ground'): 2,
    ('grass', 'ghost'): 1,
    ('grass', 'dark'): 1,
    ('grass', 'flying'): 0.5,

    # Poison
    ('poison', 'steel'): 0,
    ('poison', 'fighting'): 1,
    ('poison', 'dragon'): 1,
    ('poison', 'water'): 1,
    ('poison', 'electric'): 1,
    ('poison', 'fairy'): 2,
    ('poison', 'fire'): 1,
    ('poison', 'ice'): 1,
    ('poison', 'bug'): 1,
    ('poison', 'normal'): 1,
    ('poison', 'grass'): 2,
    ('poison', 'poison'): 0.5,
    ('poison', 'psychic'): 1,
    ('poison', 'rock'): 0.5,
    ('poison', 'ground'): 0.5,
    ('poison', 'ghost'): 0.5,
    ('poison', 'dark'): 1,
    ('poison', 'flying'): 1,

    # Psychic
    ('psychic', 'steel'): 0.5,
    ('psychic', 'fighting'): 2,
    ('psychic', 'dragon'): 1,
    ('psychic', 'water'): 1,
    ('psychic', 'electric'): 1,
    ('psychic', 'fairy'): 1,
    ('psychic', 'fire'): 1,
    ('psychic', 'ice'): 1,
    ('psychic', 'bug'): 1,
    ('psychic', 'normal'): 1,
    ('psychic', 'grass'): 1,
    ('psychic', 'poison'): 2,
    ('psychic', 'psychic'): 0.5,
    ('psychic', 'rock'): 1,
    ('psychic', 'ground'): 1,
    ('psychic', 'ghost'): 1,
    ('psychic', 'dark'): 0,
    ('psychic', 'flying'): 1,

    # Rock
    ('rock', 'steel'): 0.5,
    ('rock', 'fighting'): 0.5,
    ('rock', 'dragon'): 1,
    ('rock', 'water'): 1,
    ('rock', 'electric'): 1,
    ('rock', 'fairy'): 1,
    ('rock', 'fire'): 2,
    ('rock', 'ice'): 2,
    ('rock', 'bug'): 2,
    ('rock', 'normal'): 1,
    ('rock', 'grass'): 1,
    ('rock', 'poison'): 1,
    ('rock', 'psychic'): 1,
    ('rock', 'rock'): 1,
    ('rock', 'ground'): 0.5,
    ('rock', 'ghost'): 1,
    ('rock', 'dark'): 1,
    ('rock', 'flying'): 2,

    # Ground
    ('ground', 'steel'): 2,
    ('ground', 'fighting'): 1,
    ('ground', 'dragon'): 1,
    ('ground', 'water'): 1,
    ('ground', 'electric'): 2,
    ('ground', 'fairy'): 1,
    ('ground', 'fire'): 2,
    ('ground', 'ice'): 1,
    ('ground', 'bug'): 0.5,
    ('ground', 'normal'): 1,
    ('ground', 'grass'): 0.5,
    ('ground', 'poison'): 2,
    ('ground', 'psychic'): 1,
    ('ground', 'rock'): 2,
    ('ground', 'ground'): 1,
    ('ground', 'ghost'): 1,
    ('ground', 'dark'): 1,
    ('ground', 'flying'): 0,

    # Ghost
    ('ghost', 'steel'): 1,
    ('ghost', 'fighting'): 1,
    ('ghost', 'dragon'): 1,
    ('ghost', 'water'): 1,
    ('ghost', 'electric'): 1,
    ('ghost', 'fairy'): 1,
    ('ghost', 'fire'): 1,
    ('ghost', 'ice'): 1,
    ('ghost', 'bug'): 1,
    ('ghost', 'normal'): 0,
    ('ghost', 'grass'): 1,
    ('ghost', 'poison'): 1,
    ('ghost', 'psychic'): 2,
    ('ghost', 'rock'): 1,
    ('ghost', 'ground'): 1,
    ('ghost', 'ghost'): 2,
    ('ghost', 'dark'): 0.5,
    ('ghost', 'flying'): 1,

    # Dark
    ('dark', 'steel'): 1,
    ('dark', 'fighting'): 0.5,
    ('dark', 'dragon'): 1,
    ('dark', 'water'): 1,
    ('dark', 'electric'): 1,
    ('dark', 'fairy'): 0.5,
    ('dark', 'fire'): 1,
    ('dark', 'ice'): 1,
    ('dark', 'bug'): 1,
    ('dark', 'normal'): 1,
    ('dark', 'grass'): 1,
    ('dark', 'poison'): 1,
    ('dark', 'psychic'): 2,
    ('dark', 'rock'): 1,
    ('dark', 'ground'): 1,
    ('dark', 'ghost'): 2,
    ('dark', 'dark'): 0.5,
    ('dark', 'flying'): 1,

    # Flying
    ('flying', 'steel'): 1,
    ('flying', 'fighting'): 2,
    ('flying', 'dragon'): 1,
    ('flying', 'water'): 1,
    ('flying', 'electric'): 0.5,
    ('flying', 'fairy'): 1,
    ('flying', 'fire'): 1,
    ('flying', 'ice'): 1,
    ('flying', 'bug'): 2,
    ('flying', 'normal'): 1,
    ('flying', 'grass'): 2,
    ('flying', 'poison'): 1,
    ('flying', 'psychic'): 1,
    ('flying', 'rock'): 0.5,
    ('flying', 'ground'): 1,
    ('flying', 'ghost'): 1,
    ('flying', 'dark'): 1,
    ('flying', 'flying'): 1,
}