# Pokemon multiplier type dictionnary

type_multiplier = {
    ('steel', 'steel'): 1,
    ('steel', 'fighting'): 2,
    ('steel', 'dragon'): 1,
    ('steel', 'water'): 1,
    ('steel', 'electric'): 1,
    ('steel', 'fairy'): 1,
    ('steel', 'fire'): 0.5,
    ('steel', 'ice'): 1,
    ('steel', 'bug'): 1,
    ('steel', 'normal'): 1,
    ('steel', 'grass'): 1,
    ('steel', 'poison'): 1,
    ('steel', 'psychic'): 1,
    ('steel', 'rock'): 1,
    ('steel', 'ground'): 1,
    ('steel', 'ghost'): 1,
    ('steel', 'dark'): 1,
    ('steel', 'flying'): 1,

    ('fighting', 'steel'): 0.5,
    ('fighting', 'fighting'): 1,
    ('fighting', 'dragon'): 1,
    ('fighting', 'water'): 1,
    ('fighting', 'electric'): 1,
    ('fighting', 'fairy'): 0.5,
    ('fighting', 'fire'): 1,
    ('fighting', 'ice'): 1,
    ('fighting', 'bug'): 1,
    ('fighting', 'normal'): 1,
    ('fighting', 'grass'): 1,
    ('fighting', 'poison'): 1,
    ('fighting', 'psychic'): 1,
    ('fighting', 'rock'): 1,
    ('fighting', 'ground'): 1,
    ('fighting', 'ghost'): 1,
    ('fighting', 'dark'): 1,
    ('fighting', 'flying'): 1, 

    ('dragon', 'steel'): 1,
    ('dragon', 'fighting'): 1,
    ('dragon', 'dragon'): 2,
    ('dragon', 'water'): 1,
    ('dragon', 'electric'): 1,
    ('dragon', 'fairy'): 0.5,
    ('dragon', 'fire'): 1,
    ('dragon', 'ice'): 1,
    ('dragon', 'bug'): 1,
    ('dragon', 'normal'): 1,
    ('dragon', 'grass'): 1,
    ('dragon', 'poison'): 1,
    ('dragon', 'psychic'): 1,
    ('dragon', 'rock'): 1,
    ('dragon', 'ground'): 1,
    ('dragon', 'ghost'): 1,
    ('dragon', 'dark'): 1,
    ('dragon', 'flying'): 1, 

    ('water', 'steel'): 1,
    ('water', 'fighting'): 1,
    ('water', 'dragon'): 1,
    ('water', 'water'): 1,
    ('water', 'electric'): 1,
    ('water', 'fairy'): 1,
    ('water', 'fire'): 2,
    ('water', 'ice'): 1,
    ('water', 'bug'): 1,
    ('water', 'normal'): 1,
    ('water', 'grass'): 0.5,
    ('water', 'poison'): 1,
    ('water', 'psychic'): 1,
    ('water', 'rock'): 1,
    ('water', 'ground'): 1,
    ('water', 'ghost'): 1,
    ('water', 'dark'): 1,
    ('water', 'flying'): 1,


}